// Package pantoapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package pantoapi

// Defines values for DecideConsentRequestStatus.
const (
	DecideConsentRequestStatusDenied  DecideConsentRequestStatus = "denied"
	DecideConsentRequestStatusGranted DecideConsentRequestStatus = "granted"
)

// Defines values for ObservationConsentItemStatus.
const (
	ObservationConsentItemStatusDenied  ObservationConsentItemStatus = "denied"
	ObservationConsentItemStatusGranted ObservationConsentItemStatus = "granted"
	ObservationConsentItemStatusPending ObservationConsentItemStatus = "pending"
	ObservationConsentItemStatusRevoked ObservationConsentItemStatus = "revoked"
)

// Defines values for ProbeResultItemStatus.
const (
	Blocked ProbeResultItemStatus = "blocked"
	Error   ProbeResultItemStatus = "error"
	Ok      ProbeResultItemStatus = "ok"
	Timeout ProbeResultItemStatus = "timeout"
)

// DecideConsentRequest defines model for DecideConsentRequest.
type DecideConsentRequest struct {
	// Status 决策结果
	Status DecideConsentRequestStatus `json:"status"`
}

// DecideConsentRequestStatus 决策结果
type DecideConsentRequestStatus string

// DecideConsentResponse defines model for DecideConsentResponse.
type DecideConsentResponse struct {
	NodeId  string `json:"node_id"`
	Status  string `json:"status"`
	Success bool   `json:"success"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error 错误详情描述
	Error string `json:"error"`
}

// FlowRecord defines model for FlowRecord.
type FlowRecord struct {
	CreatedAtMs    int64   `json:"created_at_ms"`
	DownloadBytes  int64   `json:"download_bytes"`
	Dst            string  `json:"dst"`
	Id             string  `json:"id"`
	LastActiveAtMs int64   `json:"last_active_at_ms"`
	Packets        int64   `json:"packets"`
	Proto          string  `json:"proto"`
	Rule           *string `json:"rule"`
	Src            string  `json:"src"`
	Target         string  `json:"target"`
	UploadBytes    int64   `json:"upload_bytes"`
}

// FlowsResponse defines model for FlowsResponse.
type FlowsResponse struct {
	Flows []FlowRecord `json:"flows"`
	Total int          `json:"total"`
}

// GroupItem defines model for GroupItem.
type GroupItem struct {
	Id       string   `json:"id"`
	Kind     string   `json:"kind"`
	Members  []string `json:"members"`
	Selected *string  `json:"selected"`
}

// GroupsResponse defines model for GroupsResponse.
type GroupsResponse struct {
	Groups []GroupItem `json:"groups"`
}

// ModeResponse defines model for ModeResponse.
type ModeResponse struct {
	GlobalExit string `json:"global_exit"`
	Mode       string `json:"mode"`
}

// ObservationConsentItem defines model for ObservationConsentItem.
type ObservationConsentItem struct {
	// DecidedAtMs 用户决策毫秒时间戳
	DecidedAtMs *int64 `json:"decided_at_ms"`

	// NodeId 节点唯一 ID
	NodeId string `json:"node_id"`

	// ProviderName 次级提供商展示名称
	ProviderName *string `json:"provider_name"`

	// RequestedAtMs 申请发起毫秒时间戳
	RequestedAtMs int64 `json:"requested_at_ms"`

	// Status 授权状态
	Status ObservationConsentItemStatus `json:"status"`

	// Url 推送用量接收端 URL
	Url string `json:"url"`
}

// ObservationConsentItemStatus 授权状态
type ObservationConsentItemStatus string

// ObservationStatusResponse defines model for ObservationStatusResponse.
type ObservationStatusResponse struct {
	ActiveNodes     int                         `json:"active_nodes"`
	LastPushResults map[string]PushResultRecord `json:"last_push_results"`
	PendingNodes    int                         `json:"pending_nodes"`
	Running         bool                        `json:"running"`
}

// ProbeResultItem defines model for ProbeResultItem.
type ProbeResultItem struct {
	Category  string                `json:"category"`
	Domain    string                `json:"domain"`
	Error     *string               `json:"error"`
	Id        string                `json:"id"`
	LatencyMs int64                 `json:"latency_ms"`
	Name      string                `json:"name"`
	Status    ProbeResultItemStatus `json:"status"`
}

// ProbeResultItemStatus defines model for ProbeResultItem.Status.
type ProbeResultItemStatus string

// ProbeSite defines model for ProbeSite.
type ProbeSite struct {
	Category    string `json:"category"`
	Description string `json:"description"`
	Domain      string `json:"domain"`
	Icon        string `json:"icon"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	Port        int    `json:"port"`
}

// ProbeSitesResponse defines model for ProbeSitesResponse.
type ProbeSitesResponse struct {
	Sites []ProbeSite `json:"sites"`
}

// ProbeTestRequest defines model for ProbeTestRequest.
type ProbeTestRequest struct {
	Category  *string `json:"category,omitempty"`
	ProxyAddr *string `json:"proxy_addr,omitempty"`
	SiteId    *string `json:"site_id,omitempty"`
	TimeoutMs *int64  `json:"timeout_ms,omitempty"`
}

// ProbeTestResponse defines model for ProbeTestResponse.
type ProbeTestResponse struct {
	Failed    int               `json:"failed"`
	Reachable int               `json:"reachable"`
	Results   []ProbeResultItem `json:"results"`
	Total     int               `json:"total"`
}

// PushResultRecord defines model for PushResultRecord.
type PushResultRecord struct {
	DownloadBytes  int64   `json:"download_bytes"`
	LastPushedAtMs int64   `json:"last_pushed_at_ms"`
	Message        *string `json:"message"`
	Success        bool    `json:"success"`
	UploadBytes    int64   `json:"upload_bytes"`
}

// SelectGroupRequest defines model for SelectGroupRequest.
type SelectGroupRequest struct {
	// Selected 目标节点 ID
	Selected string `json:"selected"`
}

// SelectGroupResponse defines model for SelectGroupResponse.
type SelectGroupResponse struct {
	GroupId  string `json:"group_id"`
	Selected string `json:"selected"`
	Success  bool   `json:"success"`
}

// SetModeRequest defines model for SetModeRequest.
type SetModeRequest struct {
	GlobalExit *string `json:"global_exit,omitempty"`
	Mode       string  `json:"mode"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	// ConnectionsCount 当前活跃连接流数量
	ConnectionsCount int64 `json:"connections_count"`

	// GlobalExit 全局出口节点或策略组 ID
	GlobalExit string `json:"global_exit"`

	// Mode 当前工作模式 (rule, global, direct)
	Mode string `json:"mode"`

	// Running 后台守护进程是否就绪运行
	Running bool         `json:"running"`
	Traffic TrafficStats `json:"traffic"`

	// UptimeSeconds 进程启动运行秒数
	UptimeSeconds int64 `json:"uptime_seconds"`
}

// TopologyGraph defines model for TopologyGraph.
type TopologyGraph struct {
	Nodes map[string]TopologyNode `json:"nodes"`
	Root  string                  `json:"root"`
}

// TopologyNode defines model for TopologyNode.
type TopologyNode struct {
	Dependents   []string `json:"dependents"`
	EffectiveMtu int      `json:"effective_mtu"`
	Id           string   `json:"id"`
	Kind         string   `json:"kind"`
	Overhead     int      `json:"overhead"`
	Path         []string `json:"path"`
	Underlay     *string  `json:"underlay"`
}

// TrafficStats defines model for TrafficStats.
type TrafficStats struct {
	// DownloadRateBps 当前下载瞬时速率 (字节/秒)
	DownloadRateBps *int64 `json:"download_rate_bps,omitempty"`

	// DownloadTotal 累计下载字节数
	DownloadTotal int64 `json:"download_total"`

	// UploadRateBps 当前上传瞬时速率 (字节/秒)
	UploadRateBps *int64 `json:"upload_rate_bps,omitempty"`

	// UploadTotal 累计上传字节数
	UploadTotal int64 `json:"upload_total"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	BuildTime string `json:"build_time"`
	Compiler  string `json:"compiler"`
	GitCommit string `json:"git_commit"`
	Version   string `json:"version"`
}

// SelectGroupMemberJSONRequestBody defines body for SelectGroupMember for application/json ContentType.
type SelectGroupMemberJSONRequestBody = SelectGroupRequest

// SetModeJSONRequestBody defines body for SetMode for application/json ContentType.
type SetModeJSONRequestBody = SetModeRequest

// DecideObservationConsentJSONRequestBody defines body for DecideObservationConsent for application/json ContentType.
type DecideObservationConsentJSONRequestBody = DecideConsentRequest

// TestProbeSitesJSONRequestBody defines body for TestProbeSites for application/json ContentType.
type TestProbeSitesJSONRequestBody = ProbeTestRequest
