// Package pantoapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package pantoapi

// ConfigResponse defines model for ConfigResponse.
type ConfigResponse struct {
	Content string `json:"content"`
}

// DelayTestRequest defines model for DelayTestRequest.
type DelayTestRequest struct {
	TimeoutMs *int    `json:"timeout_ms,omitempty"`
	Url       *string `json:"url,omitempty"`
}

// DelayTestResponse defines model for DelayTestResponse.
type DelayTestResponse struct {
	Delays map[string]int `json:"delays"`
	Id     string         `json:"id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GroupItem defines model for GroupItem.
type GroupItem struct {
	Current string          `json:"current"`
	Delays  *map[string]int `json:"delays,omitempty"`
	Id      string          `json:"id"`
	Kind    string          `json:"kind"`
	Members []string        `json:"members"`
}

// GroupsResponse defines model for GroupsResponse.
type GroupsResponse struct {
	Groups []GroupItem `json:"groups"`
}

// MagicIPCandidate defines model for MagicIPCandidate.
type MagicIPCandidate struct {
	DnsName    *string `json:"dns_name,omitempty"`
	EndpointId string  `json:"endpoint_id"`
	Hostname   string  `json:"hostname"`
	Online     bool    `json:"online"`
	Priority   int     `json:"priority"`
}

// MagicIPChoiceItem defines model for MagicIPChoiceItem.
type MagicIPChoiceItem struct {
	Endpoint     string  `json:"endpoint"`
	Ip           string  `json:"ip"`
	PeerHostname *string `json:"peer_hostname,omitempty"`
	Remember     bool    `json:"remember"`
	UpdatedAt    *string `json:"updated_at,omitempty"`
}

// MagicIPChoicesResponse defines model for MagicIPChoicesResponse.
type MagicIPChoicesResponse struct {
	Choices []MagicIPChoiceItem `json:"choices"`
}

// MagicIPConflictItem defines model for MagicIPConflictItem.
type MagicIPConflictItem struct {
	Candidates       []MagicIPCandidate `json:"candidates"`
	DetectedAt       *string            `json:"detected_at,omitempty"`
	Ip               string             `json:"ip"`
	LastUsedEndpoint string             `json:"last_used_endpoint"`
}

// MagicIPDecideRequest defines model for MagicIPDecideRequest.
type MagicIPDecideRequest struct {
	Endpoint string `json:"endpoint"`
	Ip       string `json:"ip"`
	Remember bool   `json:"remember"`
}

// MagicIPDecideResponse defines model for MagicIPDecideResponse.
type MagicIPDecideResponse struct {
	Endpoint string `json:"endpoint"`
	Ip       string `json:"ip"`
	Success  bool   `json:"success"`
}

// MagicIPDeleteResponse defines model for MagicIPDeleteResponse.
type MagicIPDeleteResponse struct {
	Ip      string `json:"ip"`
	Success bool   `json:"success"`
}

// MagicIPPendingResponse defines model for MagicIPPendingResponse.
type MagicIPPendingResponse struct {
	Conflicts []MagicIPConflictItem `json:"conflicts"`
}

// ModeResponse defines model for ModeResponse.
type ModeResponse struct {
	GlobalTarget string `json:"global_target"`
	Mode         string `json:"mode"`
}

// ProbeResultItem defines model for ProbeResultItem.
type ProbeResultItem struct {
	Chain            []string `json:"chain"`
	Domain           string   `json:"domain"`
	Error            *string  `json:"error,omitempty"`
	Id               string   `json:"id"`
	LatencyMs        int      `json:"latency_ms"`
	RuleTarget       string   `json:"rule_target"`
	SelectedEndpoint string   `json:"selected_endpoint"`
	Status           string   `json:"status"`
}

// ProbeSite defines model for ProbeSite.
type ProbeSite struct {
	Category    string `json:"category"`
	Description string `json:"description"`
	Domain      string `json:"domain"`
	Icon        string `json:"icon"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	Port        int    `json:"port"`
}

// ProbeSitesResponse defines model for ProbeSitesResponse.
type ProbeSitesResponse struct {
	Sites []ProbeSite `json:"sites"`
}

// ProbeTestRequest defines model for ProbeTestRequest.
type ProbeTestRequest struct {
	SiteId    *string `json:"site_id,omitempty"`
	TimeoutMs *int    `json:"timeout_ms,omitempty"`
}

// ProbeTestResponse defines model for ProbeTestResponse.
type ProbeTestResponse struct {
	Results []ProbeResultItem `json:"results"`
}

// RuleItem defines model for RuleItem.
type RuleItem struct {
	Payload string `json:"payload"`
	Raw     string `json:"raw"`
	Target  string `json:"target"`
	Type    string `json:"type"`
}

// RuleMatchRequest defines model for RuleMatchRequest.
type RuleMatchRequest struct {
	Host string `json:"host"`
	Port *int   `json:"port,omitempty"`
}

// RuleMatchResponse defines model for RuleMatchResponse.
type RuleMatchResponse struct {
	Chain            []string `json:"chain"`
	Matched          bool     `json:"matched"`
	RuleTarget       string   `json:"rule_target"`
	SelectedEndpoint string   `json:"selected_endpoint"`
}

// RulesResponse defines model for RulesResponse.
type RulesResponse struct {
	Rules []RuleItem `json:"rules"`
}

// SelectMemberRequest defines model for SelectMemberRequest.
type SelectMemberRequest struct {
	Selected string `json:"selected"`
}

// SelectMemberResponse defines model for SelectMemberResponse.
type SelectMemberResponse struct {
	Current string `json:"current"`
	Id      string `json:"id"`
}

// SetModeRequest defines model for SetModeRequest.
type SetModeRequest struct {
	GlobalTarget *string `json:"global_target,omitempty"`
	Mode         string  `json:"mode"`
}

// SetTailscaleExitNodeRequest defines model for SetTailscaleExitNodeRequest.
type SetTailscaleExitNodeRequest struct {
	Selected string `json:"selected"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	ActiveEndpoints int     `json:"active_endpoints"`
	ActiveGroups    int     `json:"active_groups"`
	ActiveRules     int     `json:"active_rules"`
	AssignedIp      *string `json:"assigned_ip,omitempty"`
	GlobalTarget    *string `json:"global_target,omitempty"`
	MixedPort       int     `json:"mixed_port"`
	Mode            *string `json:"mode,omitempty"`
	Running         bool    `json:"running"`
	UptimeSeconds   int     `json:"uptime_seconds"`
}

// TailscaleExitNodeItem defines model for TailscaleExitNodeItem.
type TailscaleExitNodeItem struct {
	DnsName  string   `json:"dns_name"`
	Hostname string   `json:"hostname"`
	Id       string   `json:"id"`
	Ips      []string `json:"ips"`
	Online   bool     `json:"online"`
	Selected bool     `json:"selected"`
}

// TailscaleExitNodeResult defines model for TailscaleExitNodeResult.
type TailscaleExitNodeResult struct {
	Selected string `json:"selected"`
}

// TailscaleExitNodesResponse defines model for TailscaleExitNodesResponse.
type TailscaleExitNodesResponse struct {
	Nodes []TailscaleExitNodeItem `json:"nodes"`
}

// TopologyNode defines model for TopologyNode.
type TopologyNode struct {
	Dependents   *[]string `json:"dependents,omitempty"`
	EffectiveMtu int       `json:"effective_mtu"`
	Id           string    `json:"id"`
	Kind         string    `json:"kind"`
	Overhead     int       `json:"overhead"`
	Path         []string  `json:"path"`
	Underlay     *string   `json:"underlay,omitempty"`
}

// TopologyResponse defines model for TopologyResponse.
type TopologyResponse struct {
	Nodes []TopologyNode `json:"nodes"`
}

// TrafficResponse defines model for TrafficResponse.
type TrafficResponse struct {
	DownBytes   int64 `json:"down_bytes"`
	DownRateBps int64 `json:"down_rate_bps"`
	UpBytes     int64 `json:"up_bytes"`
	UpRateBps   int64 `json:"up_rate_bps"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	Arch     string `json:"arch"`
	Compiler string `json:"compiler"`
	Os       string `json:"os"`
	Version  string `json:"version"`
}

// StreamProbeSitesParams defines parameters for StreamProbeSites.
type StreamProbeSitesParams struct {
	TimeoutMs *int `form:"timeout_ms,omitempty" json:"timeout_ms,omitempty"`
}

// TestGroupDelayJSONRequestBody defines body for TestGroupDelay for application/json ContentType.
type TestGroupDelayJSONRequestBody = DelayTestRequest

// SelectGroupMemberJSONRequestBody defines body for SelectGroupMember for application/json ContentType.
type SelectGroupMemberJSONRequestBody = SelectMemberRequest

// SetModeJSONRequestBody defines body for SetMode for application/json ContentType.
type SetModeJSONRequestBody = SetModeRequest

// TestProbeSitesJSONRequestBody defines body for TestProbeSites for application/json ContentType.
type TestProbeSitesJSONRequestBody = ProbeTestRequest

// MatchRuleJSONRequestBody defines body for MatchRule for application/json ContentType.
type MatchRuleJSONRequestBody = RuleMatchRequest

// SetTailscaleExitNodeJSONRequestBody defines body for SetTailscaleExitNode for application/json ContentType.
type SetTailscaleExitNodeJSONRequestBody = SetTailscaleExitNodeRequest

// DecideMagicIPJSONRequestBody defines body for DecideMagicIP for application/json ContentType.
type DecideMagicIPJSONRequestBody = MagicIPDecideRequest
